services:
  frontend:
    image: ghcr.io/mattismoel/shockmarket/frontend:main
    ports:
      - 5173:5173

  backend:
    image: ghcr.io/mattismoel/shockmarket/backend:main
    ports:
      - 8080:8080
    volumes:
      - ./backend/pb/pb_data:/pb/pb_data
      - ./backend/pb/pb_migrations:/pb/pb_migrations

volumes:
  pb_data:
