services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./frontend
          target: /app
          action: sync
          ignore:
            - node_modules/
            - .svelte-kit/
            - build/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./backend/pb/pb_data:/pb/pb_data
      - ./backend/pb/pb_migrations:/pb/pb_migrations
    develop:
      watch:
        - path: ./backend/pb/pb_migrations
          target: /pb/pb_migrations
          action: sync+restart

volumes:
  pb_data:
