services:
  frontend:
    image: ghcr.io/mattismoel/shockmarket/frontend:main
    networks:
      - proxy

  backend:
    image: ghcr.io/mattismoel/shockmarket/backend:main
    volumes:
      - pb_data:/pb/pb_data
      - pb_migrations:/pb/pb_migrations
    networks:
      - proxy

volumes:
  pb_data:
  pb_migrations:

networks:
  proxy:
    name: proxy
    external: true
