name: Publish Frontend Docker Image

env:
  REGISTRY: ghcr.io
  PACKAGE_NAME: frontend

on:
  pull_request:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/**"

  push:
    branches: ["main"]
    paths:
      - "frontend/**"
      - ".github/workflows/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log Into Registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build And Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags:
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.event.repository.name }}/${{ env.PACKAGE_NAME }}:${{ github.ref_name }}
            ${{ env.REGISTRY }}/${{ github.actor }}/${{ github.event.repository.name }}/${{ env.PACKAGE_NAME }}:${{ github.sha }}
